name: ebay_api_config

# Trading API Sandbox - https://www.x.com/developers/ebay/products/trading-api
api.sandbox.ebay.com:
    compatability: 719
    appid: WeiSong-v5applic-SBX-4c8ec878c-5d201430
    certid: SBX-c8ec878cd38d-2175-4ed7-90fb-2239
    devid: 5f568d61-c7ea-40e6-9fee-4cb3422d1ff7
    token: AgAAAA**AQAAAA**aAAAAA**MIT1Xg**nY+sHZ2PrBmdj6wVnY+sEZ2PrA2dj6wFk4aiC5WHogidj6x9nY+seQ**Ik0FAA**AAMAAA**Lm7FJsJKP/K5EffRdvx2QkLncSwRUXOcP1FZ+hgML466n1okjDBA1EyFa5wtHtBj1Oj3HThyw7qiPgzRmZTCqDaxzrOM9nzZHe2bDVj0Q3T2O+Cr73t7pn+UnoGTwWfQ1PqBizXT1hPGJlq3nfCiwKk9mG7vU1CPfnWbbe6cSwu6d/LvWs2dpvs7/tTydcZfhSvhGxmJ0avs7B2FLtyOyjycW/e3BKdW7ALJAQHzpJS+KIoGjrqmWkwWO0Zgez5A1jLZjJ74SMzcbuKMUDaNRufcWbUOVmaHqllo8FI9fssydiY43sX3nUW/JJksstgr92Ytqpjbcf1JnirdZz8XEeI70gxCc58vdSvgLxlL2avC3d4BimIN71X6iG0gaa/Le35i/YopsgWBWWx7J99JcLd6FDIVLIdxU6Z/iTAzsIL28Q0/tFGmt7yQxA+lv9uJyFtodcSoxuFJb4DjgIjHAaf70GCkzZMKM2+tZ4FEsPd9datfgAQjp1tC8YTaGmk9dCqnQ6Io9V3Vo50ZnIQU+H7EFYc1lqfwQL2SzYktV9wyqUf/zubzQU97N9mwkQchMjIjoIuAn+PdslO9OwQcy0/RBViBmYqqxn30v/c4m8vPYTYEV7C83sijbDmzujv+Ro+SGxtkohEfGXo7yhH8NIF0+zF23+UL/1pl2T0oYg+aw0jJg5rE6VA0Y+RY0aODnlEv+jH9J+moIQJLrkdON6jAORVrxfCaAriI32E+CJMSyThqHRR71XqE4USgBcFy

# Trading API - https://www.x.com/developers/ebay/products/trading-api
api.ebay.com:
    compatability: 719
    siteid: 15
    appid: WeiSong-v5applic-PRD-4c8e8a00c-895f9b6b
    certid: PRD-c8e8a00cdc2a-22bb-4946-949f-bf8a
    devid: 5f568d61-c7ea-40e6-9fee-4cb3422d1ff7
    token: AgAAAA**AQAAAA**aAAAAA**ztcwXw**nY+sHZ2PrBmdj6wVnY+sEZ2PrA2dj6MFl4SjCZmFpA6dj6x9nY+seQ**8VoGAA**AAMAAA**Cnn0xkhch990LzWFWK2o/reM6DMxxnnug9L7vj0bCUabM4PQlrpSrct3Zc7lJtwT43aZ/8raEHJmtrfzHMyd0OxazNC6EaCOa97fhFr0eqEBssvixmq7bcVzefOMb7qt9HyiDRjYLk6l0Zw/8frrgPr0Tw5v1B6w8RgMDXRLw+tKxaz3cwzVX2bwdGQzSPQeA6XtRZjQc+8EeS6YhV66gF3l/jBWhVqdZuD1qKLg03TaERyj+3Bmi8RAth+M8VldSd4+T7IigSBqOD3wgCD3sZUt9p5k1+zei8KImGuVZNFzt9cvK4nC20P1L/rAkK0kwIg1RX8Ex+/CnBCuGOYfQEQ+2EcI9d5O3CfjQ/4/QqTZZ11+sNYKezSJRk5lZZXcTFgqH2ydlfw3v823J1qEk6gmtZvjwL4xSG+b9jtX9kNELVZ2vNYAxppPZwb3gvDFd6lPJ8OoWe9x6rDgt4RBSkc0H2DOkeI6CE1vqXAXB9k/dVEDQg+LXdBrLfD1CkEVUhTeRAllkpAFqbqXVZPydSHSSVqTbbYZVU9bfT4/dfNldNxIkALTeUqH3IcoLQA+QuhoBPWzhbYzvHbOJ6H2SwJiguSCG7/+v+TLgqHedcbhq+56JKbUtLiFRUjN+h/iPFCmGLEaUFC0+O843jZKnCr8BNIjhko7DRDVAipqVcsxeOV8egtGltBmsS/s1JKGCHp/I1PPn6iR18dVJ0Fmu5m00DIbhiRIN/4O15KnRpdip5EBmf1u7nRpgXSYj81M
# Finding API - https://www.x.com/developers/ebay/products/finding-api
svcs.ebay.com:
    appid: WeiSong-v5applic-SBX-4c8ec878c-5d201430
    version: 1.0.0

# Shopping API - https://www.x.com/developers/ebay/products/shopping-api
open.api.ebay.com:
    appid: WeiSong-v5applic-SBX-4c8ec878c-5d201430
    version: 671